nav_msgs/OccupancyGrid map1
nav_msgs/OccupancyGrid map2
uint8 number_of_hypotheses
---
geometry_msgs/TransformStamped[] transforms    # Standard ROS transformation from map1 to map2
float32[] success_coefficients                 # An estimate of how well the alignment went. 
                                               # This should lie between 0 and 1. A value of -1 indicates an error.
                                               # Please note that the preferred way of indicating an error is by returning
                                               # false on the service callback.
duration duration 							   # The duration of the alignment process. Could be used to adjust the number of hypotheses.
